# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1175, 614)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_design = QtWidgets.QWidget(Dialog)
        self.widget_design.setStyleSheet("\n"
"   QWidget{\n"
"    background-color: rgb(33, 37, 43);\n"
"    color: rgb(208, 208, 208);\n"
"    font-size: 10pt;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
" QScrollBar {\n"
"border: none;                                                /* без границ */\n"
"    border-right:5px solid rgb(211, 211, 211);;    /* С правой красной раницей */\n"
" }\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/* Ползунок */\n"
" QScrollBar::handle:vertical {    \n"
"    background:rgb(255, 255, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
"/*Нижняя стрелка*/\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/*Верхняя стрелка*/\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/* Цвета нижних и верхних стрелок */\n"
" QScrollBar::up-arrow:vertical{\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
" }\n"
"QScrollBar::down-arrow:vertical{\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(255, 255, 255);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QRadioButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"}\n"
"/* срабатывает, при нажатии*/\n"
"QRadioButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color:  rgb(0, 0, 0);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox */\n"
"/* Стандартное состояние*/\n"
"QCheckBox{\n"
"    padding-left: 8px;        /* Отступ слева */\n"
"    padding-right: -8px;    /* Отступ справа */\n"
"}\n"
"\n"
"/* Состояние - не выбран*/\n"
"QCheckBox::indicator:unchecked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_error_red_24dp.svg)\n"
"}\n"
"\n"
"/* Состояние -  выбран*/\n"
"QCheckBox::indicator:checked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_ok_grean_24dp.svg);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QPushButton */\n"
"/*Стандартное состояние для кнопки*/\n"
"QPushButton {\n"
"    font-size: 12pt;\n"
"    background-color:rgb(37, 41, 48);/* задает цвет фона */\n"
"    display: inline-block;                            /* пределяет, будет ли элемент обрабатываться как блочный или встроенный элемент */\n"
"    border: 1px solid rgb(52, 59, 72);        /* задает границу элемента */\n"
"\n"
"    /* задает иконку */\n"
"    background-position: left center;                            /* выравнивание иконки */\n"
"    background-repeat: no-repeat;                                /* повторять иконку */\n"
"} \n"
"\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QPushButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"    border: none;                                                /* без границ */\n"
"    border-left:4px solid rgb(208, 208, 208);    /* С правой красной раницей */\n"
"}\n"
"\n"
"\n"
"/* срабатывает, при нажатии*/\n"
"QPushButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color: rgb(181, 181, 181);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit */\n"
"/* Стиль по умолчанию */\n"
"QLineEdit:enabled{\n"
"    background-color:rgb(44, 49, 58); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"}\n"
"\n"
"/* Если поле отключено */\n"
"QLineEdit:disabled {\n"
"    background-color:  rgba(67, 74, 88, 0); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"    color: rgb(67, 74, 88);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QGroupBox */\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);    /* задает цвет шрифта */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"\n"
"QTableWidget {    \n"
"    gridline-color: rgb(136, 136, 136);\n"
"    border-top: 1px solid rgb(54, 60, 74);\n"
"    border-bottom: 1px solid  rgb(54, 60, 74);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(72, 81, 94);\n"
"}\n"
"QHeaderView { qproperty-defaultAlignment: AlignCenter; }\n"
"/*Цвет верхнего и левого поля*/\n"
"QHeaderView::section{\n"
"    background-color:rgb(37, 41, 48);\n"
"    border-style: none;\n"
"border: 1px solid rgb(136, 136, 136);\n"
"}\n"
"/*Кнопка в верхнем левом углу*/\n"
"QTableCornerButton::section {background-color:rgb(33, 37, 43); }\n"
"\n"
"QWidget#widget_loading_data {\n"
"    border-bottom: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QWidget#widget_processing {\n"
"    border-top: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QScrollArea{\n"
"border: none;\n"
"}")
        self.widget_design.setObjectName("widget_design")
        self.layout_design = QtWidgets.QHBoxLayout(self.widget_design)
        self.layout_design.setContentsMargins(0, 0, 0, 0)
        self.layout_design.setSpacing(3)
        self.layout_design.setObjectName("layout_design")
        self.widget_menu = QtWidgets.QWidget(self.widget_design)
        self.widget_menu.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_menu.setObjectName("widget_menu")
        self.layout_menu = QtWidgets.QVBoxLayout(self.widget_menu)
        self.layout_menu.setContentsMargins(0, 0, 0, 6)
        self.layout_menu.setSpacing(6)
        self.layout_menu.setObjectName("layout_menu")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_menu)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 204, 473))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, -1, 3, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_tab_start_parameters = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_tab_start_parameters.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_tab_start_parameters.setCheckable(True)
        self.pushButton_tab_start_parameters.setChecked(True)
        self.pushButton_tab_start_parameters.setObjectName("pushButton_tab_start_parameters")
        self.verticalLayout_2.addWidget(self.pushButton_tab_start_parameters)
        self.widget_start_parameters = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_start_parameters.setStyleSheet("")
        self.widget_start_parameters.setObjectName("widget_start_parameters")
        self.layout_start_parameters = QtWidgets.QVBoxLayout(self.widget_start_parameters)
        self.layout_start_parameters.setContentsMargins(0, 0, 0, 15)
        self.layout_start_parameters.setSpacing(6)
        self.layout_start_parameters.setObjectName("layout_start_parameters")
        self.groupBox_area_size = QtWidgets.QGroupBox(self.widget_start_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_area_size.sizePolicy().hasHeightForWidth())
        self.groupBox_area_size.setSizePolicy(sizePolicy)
        self.groupBox_area_size.setObjectName("groupBox_area_size")
        self.layout_area_size = QtWidgets.QVBoxLayout(self.groupBox_area_size)
        self.layout_area_size.setContentsMargins(0, 0, 0, 9)
        self.layout_area_size.setSpacing(5)
        self.layout_area_size.setObjectName("layout_area_size")
        self.widget_elements_on_side = QtWidgets.QWidget(self.groupBox_area_size)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_elements_on_side.sizePolicy().hasHeightForWidth())
        self.widget_elements_on_side.setSizePolicy(sizePolicy)
        self.widget_elements_on_side.setObjectName("widget_elements_on_side")
        self.layout_elements_on_side = QtWidgets.QHBoxLayout(self.widget_elements_on_side)
        self.layout_elements_on_side.setContentsMargins(-1, 0, -1, 0)
        self.layout_elements_on_side.setObjectName("layout_elements_on_side")
        self.lineEdit_elements_on_side = QtWidgets.QLineEdit(self.widget_elements_on_side)
        self.lineEdit_elements_on_side.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_elements_on_side.setObjectName("lineEdit_elements_on_side")
        self.layout_elements_on_side.addWidget(self.lineEdit_elements_on_side)
        self.layout_area_size.addWidget(self.widget_elements_on_side)
        self.layout_start_parameters.addWidget(self.groupBox_area_size)
        self.groupBox_area_parameters = QtWidgets.QGroupBox(self.widget_start_parameters)
        self.groupBox_area_parameters.setObjectName("groupBox_area_parameters")
        self.layout_dome_1 = QtWidgets.QVBoxLayout(self.groupBox_area_parameters)
        self.layout_dome_1.setContentsMargins(0, 0, 0, 9)
        self.layout_dome_1.setSpacing(5)
        self.layout_dome_1.setObjectName("layout_dome_1")
        self.widget_x0 = QtWidgets.QWidget(self.groupBox_area_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_x0.sizePolicy().hasHeightForWidth())
        self.widget_x0.setSizePolicy(sizePolicy)
        self.widget_x0.setObjectName("widget_x0")
        self.layout_x0 = QtWidgets.QHBoxLayout(self.widget_x0)
        self.layout_x0.setContentsMargins(-1, 0, -1, 0)
        self.layout_x0.setObjectName("layout_x0")
        self.label_text_x0 = QtWidgets.QLabel(self.widget_x0)
        self.label_text_x0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_x0.setObjectName("label_text_x0")
        self.layout_x0.addWidget(self.label_text_x0)
        self.lineEdit_x0 = QtWidgets.QLineEdit(self.widget_x0)
        self.lineEdit_x0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_x0.setObjectName("lineEdit_x0")
        self.layout_x0.addWidget(self.lineEdit_x0)
        self.layout_x0.setStretch(0, 1)
        self.layout_x0.setStretch(1, 1)
        self.layout_dome_1.addWidget(self.widget_x0)
        self.widget_y0 = QtWidgets.QWidget(self.groupBox_area_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_y0.sizePolicy().hasHeightForWidth())
        self.widget_y0.setSizePolicy(sizePolicy)
        self.widget_y0.setObjectName("widget_y0")
        self.layout_y0 = QtWidgets.QHBoxLayout(self.widget_y0)
        self.layout_y0.setContentsMargins(-1, 0, -1, 0)
        self.layout_y0.setObjectName("layout_y0")
        self.label_text_y0 = QtWidgets.QLabel(self.widget_y0)
        self.label_text_y0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_y0.setObjectName("label_text_y0")
        self.layout_y0.addWidget(self.label_text_y0)
        self.lineEdit_y0 = QtWidgets.QLineEdit(self.widget_y0)
        self.lineEdit_y0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_y0.setObjectName("lineEdit_y0")
        self.layout_y0.addWidget(self.lineEdit_y0)
        self.layout_y0.setStretch(0, 1)
        self.layout_y0.setStretch(1, 1)
        self.layout_dome_1.addWidget(self.widget_y0)
        self.layout_start_parameters.addWidget(self.groupBox_area_parameters)
        self.groupBox_substance_parameters = QtWidgets.QGroupBox(self.widget_start_parameters)
        self.groupBox_substance_parameters.setObjectName("groupBox_substance_parameters")
        self.layout_substance_parameters = QtWidgets.QVBoxLayout(self.groupBox_substance_parameters)
        self.layout_substance_parameters.setContentsMargins(0, 0, 0, 9)
        self.layout_substance_parameters.setSpacing(5)
        self.layout_substance_parameters.setObjectName("layout_substance_parameters")
        self.widget_temperature = QtWidgets.QWidget(self.groupBox_substance_parameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_temperature.sizePolicy().hasHeightForWidth())
        self.widget_temperature.setSizePolicy(sizePolicy)
        self.widget_temperature.setObjectName("widget_temperature")
        self.layout_temperature = QtWidgets.QHBoxLayout(self.widget_temperature)
        self.layout_temperature.setContentsMargins(-1, 0, -1, 0)
        self.layout_temperature.setObjectName("layout_temperature")
        self.label_text_temperature = QtWidgets.QLabel(self.widget_temperature)
        self.label_text_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_temperature.setObjectName("label_text_temperature")
        self.layout_temperature.addWidget(self.label_text_temperature)
        self.lineEdit_temperature = QtWidgets.QLineEdit(self.widget_temperature)
        self.lineEdit_temperature.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_temperature.setObjectName("lineEdit_temperature")
        self.layout_temperature.addWidget(self.lineEdit_temperature)
        self.layout_temperature.setStretch(0, 1)
        self.layout_temperature.setStretch(1, 1)
        self.layout_substance_parameters.addWidget(self.widget_temperature)
        self.layout_start_parameters.addWidget(self.groupBox_substance_parameters)
        self.verticalLayout_2.addWidget(self.widget_start_parameters)
        self.pushButton_options = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_options.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_options.setCheckable(True)
        self.pushButton_options.setChecked(True)
        self.pushButton_options.setObjectName("pushButton_options")
        self.verticalLayout_2.addWidget(self.pushButton_options)
        self.widget_options = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_options.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_options.setObjectName("widget_options")
        self.layout_options = QtWidgets.QVBoxLayout(self.widget_options)
        self.layout_options.setContentsMargins(0, 0, 0, 20)
        self.layout_options.setObjectName("layout_options")
        self.groupBox_iteration_process = QtWidgets.QGroupBox(self.widget_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_iteration_process.sizePolicy().hasHeightForWidth())
        self.groupBox_iteration_process.setSizePolicy(sizePolicy)
        self.groupBox_iteration_process.setObjectName("groupBox_iteration_process")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_iteration_process)
        self.verticalLayout.setContentsMargins(9, 5, 9, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_time_step = QtWidgets.QWidget(self.groupBox_iteration_process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_time_step.sizePolicy().hasHeightForWidth())
        self.widget_time_step.setSizePolicy(sizePolicy)
        self.widget_time_step.setObjectName("widget_time_step")
        self.layout_time_step = QtWidgets.QHBoxLayout(self.widget_time_step)
        self.layout_time_step.setContentsMargins(-1, 0, -1, 0)
        self.layout_time_step.setObjectName("layout_time_step")
        self.label_text_time_step = QtWidgets.QLabel(self.widget_time_step)
        self.label_text_time_step.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_time_step.setObjectName("label_text_time_step")
        self.layout_time_step.addWidget(self.label_text_time_step)
        self.lineEdit_time_step = QtWidgets.QLineEdit(self.widget_time_step)
        self.lineEdit_time_step.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time_step.setObjectName("lineEdit_time_step")
        self.layout_time_step.addWidget(self.lineEdit_time_step)
        self.layout_time_step.setStretch(0, 1)
        self.layout_time_step.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_time_step)
        self.widget_iterations = QtWidgets.QWidget(self.groupBox_iteration_process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_iterations.sizePolicy().hasHeightForWidth())
        self.widget_iterations.setSizePolicy(sizePolicy)
        self.widget_iterations.setObjectName("widget_iterations")
        self.layout_iterations = QtWidgets.QHBoxLayout(self.widget_iterations)
        self.layout_iterations.setContentsMargins(-1, 0, -1, 0)
        self.layout_iterations.setObjectName("layout_iterations")
        self.label_iterations = QtWidgets.QLabel(self.widget_iterations)
        self.label_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.label_iterations.setObjectName("label_iterations")
        self.layout_iterations.addWidget(self.label_iterations)
        self.lineEdit_iterations = QtWidgets.QLineEdit(self.widget_iterations)
        self.lineEdit_iterations.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_iterations.setObjectName("lineEdit_iterations")
        self.layout_iterations.addWidget(self.lineEdit_iterations)
        self.layout_iterations.setStretch(0, 1)
        self.layout_iterations.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget_iterations)
        self.verticalLayout.setStretch(0, 1)
        self.layout_options.addWidget(self.groupBox_iteration_process)
        self.verticalLayout_2.addWidget(self.widget_options)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_menu.addWidget(self.scrollArea)
        self.widget_processing = QtWidgets.QWidget(self.widget_menu)
        self.widget_processing.setObjectName("widget_processing")
        self.layout_processing = QtWidgets.QVBoxLayout(self.widget_processing)
        self.layout_processing.setContentsMargins(0, 2, 0, 0)
        self.layout_processing.setSpacing(0)
        self.layout_processing.setObjectName("layout_processing")
        self.pushButton_initial_state = QtWidgets.QPushButton(self.widget_processing)
        self.pushButton_initial_state.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_initial_state.setObjectName("pushButton_initial_state")
        self.layout_processing.addWidget(self.pushButton_initial_state)
        self.pushButton_start_processing = QtWidgets.QPushButton(self.widget_processing)
        self.pushButton_start_processing.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_start_processing.setObjectName("pushButton_start_processing")
        self.layout_processing.addWidget(self.pushButton_start_processing)
        self.widget_deviation_original_and_noise = QtWidgets.QWidget(self.widget_processing)
        self.widget_deviation_original_and_noise.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_deviation_original_and_noise.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_deviation_original_and_noise.setObjectName("widget_deviation_original_and_noise")
        self.layout_deviation_original_and_noise = QtWidgets.QHBoxLayout(self.widget_deviation_original_and_noise)
        self.layout_deviation_original_and_noise.setContentsMargins(-1, 0, -1, 0)
        self.layout_deviation_original_and_noise.setSpacing(0)
        self.layout_deviation_original_and_noise.setObjectName("layout_deviation_original_and_noise")
        self.label_text_deviation_original_and_noise = QtWidgets.QLabel(self.widget_deviation_original_and_noise)
        self.label_text_deviation_original_and_noise.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_deviation_original_and_noise.setFont(font)
        self.label_text_deviation_original_and_noise.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_deviation_original_and_noise.setObjectName("label_text_deviation_original_and_noise")
        self.layout_deviation_original_and_noise.addWidget(self.label_text_deviation_original_and_noise)
        self.label_deviation_original_and_noise = QtWidgets.QLabel(self.widget_deviation_original_and_noise)
        self.label_deviation_original_and_noise.setText("")
        self.label_deviation_original_and_noise.setAlignment(QtCore.Qt.AlignCenter)
        self.label_deviation_original_and_noise.setObjectName("label_deviation_original_and_noise")
        self.layout_deviation_original_and_noise.addWidget(self.label_deviation_original_and_noise)
        self.layout_deviation_original_and_noise.setStretch(0, 2)
        self.layout_deviation_original_and_noise.setStretch(1, 1)
        self.layout_processing.addWidget(self.widget_deviation_original_and_noise)
        self.widget_deviation_original_and_received = QtWidgets.QWidget(self.widget_processing)
        self.widget_deviation_original_and_received.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_deviation_original_and_received.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_deviation_original_and_received.setObjectName("widget_deviation_original_and_received")
        self.layout_deviation_original_and_received = QtWidgets.QHBoxLayout(self.widget_deviation_original_and_received)
        self.layout_deviation_original_and_received.setContentsMargins(-1, 0, -1, 0)
        self.layout_deviation_original_and_received.setSpacing(0)
        self.layout_deviation_original_and_received.setObjectName("layout_deviation_original_and_received")
        self.label_text_deviation_original_and_received = QtWidgets.QLabel(self.widget_deviation_original_and_received)
        self.label_text_deviation_original_and_received.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_text_deviation_original_and_received.setFont(font)
        self.label_text_deviation_original_and_received.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text_deviation_original_and_received.setObjectName("label_text_deviation_original_and_received")
        self.layout_deviation_original_and_received.addWidget(self.label_text_deviation_original_and_received)
        self.label_deviation_original_and_received = QtWidgets.QLabel(self.widget_deviation_original_and_received)
        self.label_deviation_original_and_received.setText("")
        self.label_deviation_original_and_received.setAlignment(QtCore.Qt.AlignCenter)
        self.label_deviation_original_and_received.setObjectName("label_deviation_original_and_received")
        self.layout_deviation_original_and_received.addWidget(self.label_deviation_original_and_received)
        self.layout_deviation_original_and_received.setStretch(0, 2)
        self.layout_deviation_original_and_received.setStretch(1, 1)
        self.layout_processing.addWidget(self.widget_deviation_original_and_received)
        self.layout_menu.addWidget(self.widget_processing)
        self.layout_design.addWidget(self.widget_menu)
        self.widget_main = QtWidgets.QWidget(self.widget_design)
        self.widget_main.setStyleSheet("QWidget{\n"
"background-color: rgb(240, 240, 240);\n"
"color: rgb(0, 0, 0);\n"
"}")
        self.widget_main.setObjectName("widget_main")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_main)
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_plot_1 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.layout_plot_1 = QtWidgets.QVBoxLayout(self.widget_plot_1)
        self.layout_plot_1.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_1.setSpacing(0)
        self.layout_plot_1.setObjectName("layout_plot_1")
        self.gridLayout.addWidget(self.widget_plot_1, 0, 0, 1, 1)
        self.widget_plot_2 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.layout_plot_2 = QtWidgets.QVBoxLayout(self.widget_plot_2)
        self.layout_plot_2.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_2.setSpacing(0)
        self.layout_plot_2.setObjectName("layout_plot_2")
        self.gridLayout.addWidget(self.widget_plot_2, 0, 1, 1, 1)
        self.widget_plot_3 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_3.setObjectName("widget_plot_3")
        self.layout_plot_3 = QtWidgets.QVBoxLayout(self.widget_plot_3)
        self.layout_plot_3.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_3.setSpacing(0)
        self.layout_plot_3.setObjectName("layout_plot_3")
        self.gridLayout.addWidget(self.widget_plot_3, 1, 0, 1, 1)
        self.widget_plot_4 = QtWidgets.QWidget(self.widget_main)
        self.widget_plot_4.setObjectName("widget_plot_4")
        self.layout_plot_4 = QtWidgets.QVBoxLayout(self.widget_plot_4)
        self.layout_plot_4.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_4.setSpacing(0)
        self.layout_plot_4.setObjectName("layout_plot_4")
        self.gridLayout.addWidget(self.widget_plot_4, 1, 1, 1, 1)
        self.layout_design.addWidget(self.widget_main)
        self.horizontalLayout.addWidget(self.widget_design)

        self.retranslateUi(Dialog)
        self.pushButton_options.clicked['bool'].connect(self.widget_options.setVisible) # type: ignore
        self.pushButton_tab_start_parameters.clicked['bool'].connect(self.widget_start_parameters.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Фильтрация изображения"))
        self.pushButton_tab_start_parameters.setText(_translate("Dialog", "Нач. Параметры"))
        self.groupBox_area_size.setTitle(_translate("Dialog", "Частиц в ширину"))
        self.lineEdit_elements_on_side.setText(_translate("Dialog", "20"))
        self.groupBox_area_parameters.setTitle(_translate("Dialog", "Параметры области"))
        self.label_text_x0.setText(_translate("Dialog", "x0"))
        self.lineEdit_x0.setText(_translate("Dialog", "0"))
        self.label_text_y0.setText(_translate("Dialog", "y0"))
        self.lineEdit_y0.setText(_translate("Dialog", "0"))
        self.groupBox_substance_parameters.setTitle(_translate("Dialog", "Параметры вещества"))
        self.label_text_temperature.setText(_translate("Dialog", "Температура"))
        self.lineEdit_temperature.setText(_translate("Dialog", "300"))
        self.pushButton_options.setText(_translate("Dialog", "Параметры"))
        self.groupBox_iteration_process.setTitle(_translate("Dialog", "Итерационный процесс"))
        self.label_text_time_step.setText(_translate("Dialog", "Шаг по времени 10^"))
        self.lineEdit_time_step.setText(_translate("Dialog", "4"))
        self.label_iterations.setText(_translate("Dialog", "Итераций"))
        self.lineEdit_iterations.setText(_translate("Dialog", "20"))
        self.pushButton_initial_state.setText(_translate("Dialog", "Начальное состояние"))
        self.pushButton_start_processing.setText(_translate("Dialog", "Обработка"))
        self.label_text_deviation_original_and_noise.setText(_translate("Dialog", "ℰ_org_noise"))
        self.label_text_deviation_original_and_received.setText(_translate("Dialog", "ℰ_org_received"))
